-- Ejecutar manualmente en PostgreSQL dentro de la base de datos sistema_reservas.
-- Este archivo no se ejecuta automáticamente desde la aplicación.

CREATE TABLE IF NOT EXISTS roles (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO roles (id, nombre)
VALUES
  (1, 'Cliente'),
  (2, 'Empleado'),
  (3, 'Administrador')
ON CONFLICT (id) DO UPDATE SET nombre = EXCLUDED.nombre;

SELECT setval(
  pg_get_serial_sequence('roles', 'id'),
  (SELECT MAX(id) FROM roles)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGSERIAL PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  apellido VARCHAR(80) NOT NULL,
  correo VARCHAR(255) NOT NULL UNIQUE,
  contrasena TEXT NOT NULL,
  rol_id SMALLINT NOT NULL DEFAULT 1 REFERENCES roles(id),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Si ya tenías una tabla usuarios con una columna rol de texto,
-- ejecuta este bloque una sola vez antes de usar la estructura nueva.
--
-- ALTER TABLE usuarios ADD COLUMN rol_id SMALLINT;
-- UPDATE usuarios AS usuario
-- SET rol_id = roles.id
-- FROM roles
-- WHERE roles.nombre = usuario.rol;
-- UPDATE usuarios SET rol_id = 1 WHERE rol_id IS NULL;
-- ALTER TABLE usuarios ALTER COLUMN rol_id SET DEFAULT 1;
-- ALTER TABLE usuarios ALTER COLUMN rol_id SET NOT NULL;
-- ALTER TABLE usuarios
--   ADD CONSTRAINT usuarios_rol_id_fkey
--   FOREIGN KEY (rol_id) REFERENCES roles(id);
-- ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_rol_valido;
-- ALTER TABLE usuarios DROP COLUMN rol;

-- Si la tabla ya tenía contrasena_hasheada, ejecuta también:
-- ALTER TABLE usuarios RENAME COLUMN contrasena_hasheada TO contrasena;
